# Generated by Django 4.1.3 on 2022-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_category_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('IT', 'Teachnology'), ('PTG', 'Photography'), ('LS', 'Life styles')], max_length=30),
        ),
    ]
